services:
  - type: web
    name: automobile-parts-ecommerce
    env: node
    plan: free
    region: oregon
    buildCommand: rm -rf .next node_modules/.cache && npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health